AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates an S3 Bucket
Parameters:
  BucketName:
    Type: String
    Description: "Unique S3 Bucket Name."
  KMSKey:
    Type: String
    Default: ''
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref KMSKey
              SSEAlgorithm: aws:kms
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 2555
            ExpiredObjectDeleteMarker: false
            Id: delete-after-10y
            NoncurrentVersionExpiration:
              NoncurrentDays: 2555
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: application
          Value: jfrog-artifactory
        - Key: build-engineer
          Value: raghu vamsi
        - Key: environment
          Value: prd